# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.URLField(default='url'),
            preserve_default=False,
        ),
    ]
